name: nectar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  auto_route: ^8.1.3
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  get_it: ^7.7.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onbording.png
    - assets/icons/logo-transparent.png

flutter_icons:
  image_path: "assets/icons/logo.png" 
  android: true
  ios: true
